---
- name: Change network configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"
  
  tasks:
    - name: Check current network configuration
      command: ip addr show {{ target_interface }}
      register: current_network
      changed_when: false

    - name: Display current network config
      debug:
        var: current_network.stdout

    - name: Create backup of current interfaces file in /tmp
      copy:
        src: /etc/network/interfaces
        dest: "/tmp/interfaces.backup.before"
        remote_src: yes
        mode: '0644'

    - name: Read current interfaces file
      slurp:
        src: /etc/network/interfaces
      register: interfaces_content

    - name: Remove existing configuration for target interface using replace
      replace:
        path: /etc/network/interfaces
        regex: '^auto {{ target_interface }}\niface {{ target_interface }}.*?(?=\n\S|\n*$)'
        replace: ''
      when: '"auto " + target_interface in interfaces_content.content | b64decode'

    - name: Add new network configuration using lineinfile
      block:
        - name: Ensure auto interface line exists
          lineinfile:
            path: /etc/network/interfaces
            line: "auto {{ target_interface }}"
            state: present

        - name: Add static IP configuration
          lineinfile:
            path: /etc/network/interfaces
            line: "iface {{ target_interface }} inet static"
            insertafter: "auto {{ target_interface }}"
            state: present

        - name: Add IP address
          lineinfile:
            path: /etc/network/interfaces
            line: "  address {{ new_ip_address }}/{{ subnet_prefix }}"
            insertafter: "iface {{ target_interface }} inet static"
            state: present

        - name: Add gateway
          lineinfile:
            path: /etc/network/interfaces
            line: "  gateway {{ gateway }}"
            insertafter: "  address {{ new_ip_address }}/{{ subnet_prefix }}"
            state: present

        - name: Add DNS servers
          lineinfile:
            path: /etc/network/interfaces
            line: "  dns-nameservers {{ dns_servers }}"
            insertafter: "  gateway {{ gateway }}"
            state: present

        - name: Add DNS domain
          lineinfile:
            path: /etc/network/interfaces
            line: "  dns-search {{ dns_domain }}"
            insertafter: "  dns-nameservers {{ dns_servers }}"
            state: present

    - name: Create manual backup of new configuration in /tmp
      copy:
        src: /etc/network/interfaces
        dest: "/tmp/interfaces.after"
        remote_src: yes
        mode: '0644'

    - name: Show new configuration
      command: cat /etc/network/interfaces
      register: new_config
      changed_when: false

    - name: Display new configuration
      debug:
        var: new_config.stdout

    - name: Test network configuration syntax
      command: ifup -n {{ target_interface }}
      register: config_test
      changed_when: false
      ignore_errors: yes

    - name: Display configuration test results
      debug:
        var: config_test.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait for reconnection with new IP (90 seconds)
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 90
        delay: 10
        sleep: 5
      connection: local
      delegate_to: localhost
      ignore_errors: yes

    - name: Final verification with new IP
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 30
      connection: local
      delegate_to: localhost
