---
- name: Change network configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"
  
  tasks:
    - name: Check current network configuration
      command: ip addr show {{ target_interface }}
      register: current_network
      changed_when: false

    - name: Display current network config
      debug:
        var: current_network.stdout

    - name: Get current IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Display current IP
      debug:
        msg: "Current IP: {{ current_ip.stdout }}"

    - name: Create backup of current interfaces file
      command: cp /etc/network/interfaces /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
      args:
        creates: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Create new interfaces configuration
      copy:
        content: |
          # Ansible managed - Network configuration
          # Created: {{ ansible_date_time.iso8601 }}
          # Old IP: {{ current_ip.stdout }}
          
          auto lo
          iface lo inet loopback

          auto {{ target_interface }}
          iface {{ target_interface }} inet static
            address {{ new_ip_address }}/{{ subnet_prefix }}
            gateway {{ gateway }}
            dns-nameservers {{ dns_servers }}
            dns-search {{ dns_domain }}
        dest: /etc/network/interfaces
        mode: '0644'

    - name: Show new configuration
      command: cat /etc/network/interfaces
      register: new_config
      changed_when: false

    - name: Display new configuration
      debug:
        var: new_config.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait a moment for network restart
      pause:
        seconds: 10

    - name: Attempt to reconnect with new IP
      wait_for_connection:
        timeout: 60
        delay: 10
        sleep: 5

    - name: Verify new IP address
      command: ip addr show {{ target_interface }}
      register: new_network_config
      ignore_errors: yes

    - name: Display new network configuration
      debug:
        msg: "New network configuration: {{ new_network_config.stdout }}"
