---
- name: Change network configuration using systemd-networkd
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Check if systemd-networkd is available
      command: systemctl status systemd-networkd
      register: networkd_status
      ignore_errors: yes
      changed_when: false

    - name: Get current IP
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Show current IP
      debug:
        msg: "Current IP: {{ current_ip.stdout }}"

    - name: Create systemd network configuration
      copy:
        content: |
          [Match]
          Name={{ target_interface }}

          [Network]
          Address={{ new_ip_address }}/{{ subnet_prefix }}
          Gateway={{ gateway }}
          DNS={{ dns_servers }}
          Domains={{ dns_domain }}
        dest: /tmp/{{ target_interface }}.network
        mode: '0644'

    - name: Try to apply systemd-networkd configuration
      block:
        - name: Stop traditional networking
          systemd:
            name: networking
            state: stopped
          ignore_errors: yes

        - name: Enable and start systemd-networkd
          systemd:
            name: systemd-networkd
            state: started
            enabled: yes
          ignore_errors: yes

        - name: Copy network configuration
          shell: |
            cp /tmp/{{ target_interface }}.network /etc/systemd/network/
            systemctl restart systemd-networkd

      when: networkd_status.rc == 0
      ignore_errors: yes

    - name: Wait for network changes
      pause:
        seconds: 10

    - name: Check new IP
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: new_ip
      changed_when: false

    - name: Display result
      debug:
        msg: |
          Network configuration attempt completed.
          Old IP: {{ current_ip.stdout }}
          Current IP: {{ new_ip.stdout }}
          Change successful: {{ new_ip_address == new_ip.stdout }}
