---
- name: Change network configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"
  
  tasks:
    - name: Check current network configuration
      command: ip addr show {{ target_interface }}
      register: current_network
      changed_when: false

    - name: Display current network config
      debug:
        var: current_network.stdout

    - name: Create backup of current network configuration
      copy:
        src: /etc/network/interfaces
        dest: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"
        remote_src: yes
        mode: '0644'

    - name: Create new network configuration
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto {{ target_interface }}
          iface {{ target_interface }} inet static
            address {{ new_ip_address }}/{{ subnet_prefix }}
            gateway {{ gateway }}
            dns-nameservers {{ dns_servers }}
            dns-search {{ dns_domain }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ target_interface }}"
        backup: yes
        backup_dir: /tmp

    - name: Show new configuration
      command: cat /etc/network/interfaces
      register: new_config
      changed_when: false

    - name: Display new configuration
      debug:
        var: new_config.stdout

    - name: Test network configuration syntax
      command: ifup -n {{ target_interface }}
      register: config_test
      changed_when: false
      ignore_errors: yes

    - name: Display configuration test results
      debug:
        var: config_test.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait for reconnection with new IP (60 seconds)
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 60
        delay: 10
        sleep: 5
      connection: local
      delegate_to: localhost
      ignore_errors: yes

    - name: Check if we can connect with new IP
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 30
      connection: local
      delegate_to: localhost

    - name: Verify new IP address
      command: ip addr show {{ target_interface }}
      register: new_network_config

    - name: Display new network configuration
      debug:
        msg: "New network configuration: {{ new_network_config.stdout }}"
