---
- name: Change network configuration using shell commands
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Get current IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Display current IP
      debug:
        msg: "Current IP: {{ current_ip.stdout }}"

    - name: Create backup using shell
      shell: |
        cp /etc/network/interfaces /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
        echo "Backup created: /tmp/interfaces.backup.{{ ansible_date_time.epoch }}"
      args:
        creates: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Create new configuration using shell and cat
      shell: |
        cat > /tmp/interfaces.new << 'EOF'
        # Ansible managed - Network configuration
        # Created: {{ ansible_date_time.iso8601 }}
        # Old IP: {{ current_ip.stdout }}
        
        auto lo
        iface lo inet loopback

        auto {{ target_interface }}
        iface {{ target_interface }} inet static
          address {{ new_ip_address }}/{{ subnet_prefix }}
          gateway {{ gateway }}
          dns-nameservers {{ dns_servers }}
          dns-search {{ dns_domain }}
        EOF

    - name: Copy new configuration to destination using shell
      shell: |
        cp /tmp/interfaces.new /etc/network/interfaces
        chmod 644 /etc/network/interfaces

    - name: Verify the file was copied
      command: cat /etc/network/interfaces
      register: final_config
      changed_when: false

    - name: Display final configuration
      debug:
        var: final_config.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait for reconnection
      wait_for_connection:
        timeout: 60
        delay: 10
        sleep: 5

    - name: Verify new IP
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: new_ip
      changed_when: false
      ignore_errors: yes

    - name: Display result
      debug:
        msg: |
          Network configuration change completed!
          Old IP: {{ current_ip.stdout }}
          New IP: {{ new_ip.stdout }}
          Success: {{ new_ip_address == new_ip.stdout }}
