---
- name: Change network configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"
  
  tasks:
    - name: Check current network configuration
      command: ip addr show {{ target_interface }}
      register: current_network
      changed_when: false

    - name: Display current network config
      debug:
        var: current_network.stdout

    - name: Create backup of current interfaces file
      command: cp /etc/network/interfaces /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
      args:
        creates: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Create new interfaces configuration using template
      template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        mode: '0644'
        backup: yes
        validate: 'ifup -n -s %s'

    - name: Show new configuration
      command: cat /etc/network/interfaces
      register: new_config
      changed_when: false

    - name: Display new configuration
      debug:
        var: new_config.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait for reconnection with new IP (90 seconds)
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 90
        delay: 10
        sleep: 5
      connection: local
      delegate_to: localhost
      ignore_errors: yes

    - name: Final verification with new IP
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 30
      connection: local
      delegate_to: localhost

    - name: Verify new IP address
      command: ip addr show {{ target_interface }}
      register: new_network_config

    - name: Display new network configuration
      debug:
        msg: "New network configuration: {{ new_network_config.stdout }}"
