---
- name: Change VM Hostname
  hosts: "{{ target_hosts | default('all') }}"
  # Убрано become: true - будем работать без повышения прав

  tasks:
    - name: Validate new hostname parameter
      fail:
        msg: "new_hostname variable must be defined. Use: -e 'new_hostname=your-hostname'"
      when: new_hostname is not defined or new_hostname | length == 0

    - name: Get current hostname
      command: hostname
      register: current_hostname
      changed_when: false

    - name: Skip if hostname already matches
      meta: end_play
      when: current_hostname.stdout == new_hostname

    - name: Update /etc/hostname file using sudo in command
      command: sudo sh -c "echo '{{ new_hostname }}' > /etc/hostname"
      changed_when: true

    - name: Set hostname temporarily using sudo
      command: sudo hostname "{{ new_hostname }}"
      changed_when: true

    - name: Verify hostname change
      command: hostname
      register: verify_hostname
      changed_when: false

    - name: Confirm successful hostname change
      assert:
        that: verify_hostname.stdout == new_hostname
        msg: "Hostname change failed. Current: {{ verify_hostname.stdout }}, Expected: {{ new_hostname }}"
