---
- name: Change VM Hostname
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_timeout: 120
    ansible_timeout: 120
  
  tasks:
    - name: Validate new hostname parameter
      fail:
        msg: "new_hostname variable must be defined and not empty. Use extra variables: -e 'new_hostname=your-hostname'"
      when: new_hostname is not defined or new_hostname | length == 0

    - name: Debug display new_hostname value
      debug:
        var: new_hostname
      when: new_hostname is defined

    - name: Validate hostname format using regex_search
      fail:
        msg: "Hostname '{{ new_hostname }}' must contain only alphanumeric characters and hyphens, 1-63 characters long"
      when: not new_hostname | regex_search('^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$')
    
    - name: Create backup directory
      file:
        path: "{{ backup_dir | default('/tmp/backups') }}"
        state: directory
        mode: '0755'
      become: true
    
    # - name: Get current hostname
    #   command: hostname -f
    #   register: current_hostname
    #   changed_when: false
    #   ignore_errors: true
    
    # - name: Get current hostname (fallback)
    #   command: hostname
    #   register: current_hostname_fallback
    #   changed_when: false
    #   when: current_hostname.rc != 0
    
    - name: Set actual current hostname fact
      set_fact:
        actual_current_hostname: "{{ current_hostname.stdout if current_hostname.rc == 0 else current_hostname_fallback.stdout }}"
    
    - name: Display current hostname information
      debug:
        msg: |
          Current hostname: {{ actual_current_hostname }}
          New hostname: {{ new_hostname }}
    
    - name: Check if hostname already matches
      debug:
        msg: "Hostname is already set to '{{ new_hostname }}'. No changes needed."
      when: actual_current_hostname == new_hostname
    
    - name: Abort if no changes needed
      meta: end_play
      when: actual_current_hostname == new_hostname
    
    - name: Check /etc/hostname file permissions
      stat:
        path: /etc/hostname
      register: hostname_stat
    
    - name: Debug file permissions
      debug:
        msg: |
          /etc/hostname permissions: {{ hostname_stat.stat.mode }}
          /etc/hostname owner: {{ hostname_stat.stat.pw_name }}:{{ hostname_stat.stat.gr_name }}
    
    - name: Backup current /etc/hostname file
      copy:
        src: /etc/hostname
        dest: "{{ backup_dir | default('/tmp/backups') }}/hostname.backup-{{ ansible_date_time.epoch }}"
        remote_src: true
        backup: true
        mode: '0644'
      become: true
      when: actual_current_hostname != new_hostname
    
    - name: Backup current /etc/hosts file
      copy:
        src: /etc/hosts
        dest: "{{ backup_dir | default('/tmp/backups') }}/hosts.backup-{{ ansible_date_time.epoch }}"
        remote_src: true
        backup: true
        mode: '0644'
      become: true
      when: actual_current_hostname != new_hostname
    
    - name: Update /etc/hostname file
      copy:
        content: "{{ new_hostname }}\n"
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
        force: yes
      become: true
      when: actual_current_hostname != new_hostname
    
    - name: Update /etc/hosts file with new hostname
      block:
        - name: Remove old entries for 127.0.1.1
          lineinfile:
            path: /etc/hosts
            regexp: '^127\.0\.1\.1\s+'
            state: absent
          become: true
        
        - name: Add new hostname entry
          lineinfile:
            path: /etc/hosts
            line: "127.0.1.1 {{ new_hostname }}"
            state: present
          become: true
        
        - name: Update localhost entry if it contains old hostname
          replace:
            path: /etc/hosts
            regexp: '^127\.0\.0\.1\s+localhost\s+{{ actual_current_hostname }}'
            replace: '127.0.0.1\tlocalhost {{ new_hostname }}'
          become: true
      when: actual_current_hostname != new_hostname
    
    - name: Set hostname temporarily (immediate effect)
      hostname:
        name: "{{ new_hostname }}"
      become: true
      when: actual_current_hostname != new_hostname
    
    - name: Verify hostname change
      command: hostname
      register: verify_hostname
      changed_when: false
    
    - name: Verify FQDN if available
      command: hostname -f
      register: verify_fqdn
      changed_when: false
      ignore_errors: true
    
    - name: Display hostname change results
      debug:
        msg: |
          Hostname change completed:
          - Temporary hostname: {{ verify_hostname.stdout }}
          - FQDN: {{ verify_fqdn.stdout if verify_fqdn.rc == 0 else 'N/A' }}
          - Expected: {{ new_hostname }}
    
    - name: Confirm successful hostname change
      assert:
        that:
          - verify_hostname.stdout == new_hostname
        msg: "Hostname change failed. Current: {{ verify_hostname.stdout }}, Expected: {{ new_hostname }}"
    
    - name: Notify about reboot requirement
      debug:
        msg: "Hostname has been changed. Some applications may require a reboot to fully recognize the new hostname."
