---
- name: Safe network configuration change
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Get current IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Display current IP
      debug:
        var: current_ip.stdout

    - name: Create complete backup
      command: cp /etc/network/interfaces /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
      args:
        creates: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Create new configuration in temporary location
      copy:
        content: |
          # Ansible managed - Network configuration
          # Backup: /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
          
          auto lo
          iface lo inet loopback

          auto {{ target_interface }}
          iface {{ target_interface }} inet static
            address {{ new_ip_address }}/{{ subnet_prefix }}
            gateway {{ gateway }}
            dns-nameservers {{ dns_servers }}
            dns-search {{ dns_domain }}
        dest: /tmp/interfaces.new
        mode: '0644'

    - name: Validate configuration syntax
      command: ifup -n -s -f /tmp/interfaces.new {{ target_interface }}
      register: validation
      changed_when: false
      ignore_errors: yes

    - name: Show validation results
      debug:
        var: validation.stdout

    - name: Apply validated configuration
      command: cp /tmp/interfaces.new /etc/network/interfaces
      args:
        creates: /etc/network/interfaces

    - name: Set correct permissions
      file:
        path: /etc/network/interfaces
        mode: '0644'
        owner: root
        group: root

    - name: Restart networking
      systemd:
        name: networking
        state: restarted
      async: 45
      poll: 0
      ignore_errors: yes

    - name: Wait for reconnection
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 120
        delay: 15
        sleep: 10
      connection: local
      delegate_to: localhost

    - name: Verify new IP
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: new_ip
      changed_when: false

    - name: Display results
      debug:
        msg: |
          Old IP: {{ current_ip.stdout }}
          New IP: {{ new_ip.stdout }}
          Change successful: {{ new_ip_address == new_ip.stdout }}
