---
- name: Change network configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Get current IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Display current IP
      debug:
        msg: "Current IP: {{ current_ip.stdout }}"

    - name: Create backup
      command: cp /etc/network/interfaces /tmp/interfaces.backup.{{ ansible_date_time.epoch }}
      args:
        creates: "/tmp/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Create new configuration
      copy:
        content: |
          # Ansible managed
          auto lo
          iface lo inet loopback

          auto {{ target_interface }}
          iface {{ target_interface }} inet static
            address {{ new_ip_address }}/{{ subnet_prefix }}
            gateway {{ gateway }}
            dns-nameservers {{ dns_servers }}
            dns-search {{ dns_domain }}
        dest: /etc/network/interfaces
        mode: '0644'

    - name: Restart networking
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0
      ignore_errors: yes

    - name: Wait for connection recovery
      wait_for_connection:
        timeout: 90
        delay: 15
        sleep: 10

    - name: Verify new IP configuration
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: new_ip
      changed_when: false

    - name: Display result
      debug:
        msg: "Network configuration changed from {{ current_ip.stdout }} to {{ new_ip.stdout }}"
