---
- name: Safe network configuration change
  hosts: all
  gather_facts: true
  become: yes
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Backup current interfaces file
      command: cp /etc/network/interfaces /etc/network/interfaces.backup.{{ ansible_date_time.epoch }}
      args:
        creates: "/etc/network/interfaces.backup.{{ ansible_date_time.epoch }}"

    - name: Remove existing configuration for target interface
      blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ target_interface }}"
        state: absent

    - name: Add new network configuration
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto {{ target_interface }}
          iface {{ target_interface }} inet static
            address {{ new_ip_address }}/{{ subnet_prefix }}
            gateway {{ gateway }}
            dns-nameservers {{ dns_servers }}
            dns-search {{ dns_domain }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ target_interface }}"
        backup: yes

    - name: Show configuration before applying
      command: cat /etc/network/interfaces
      register: interfaces_content
      changed_when: false

    - name: Display configuration
      debug:
        var: interfaces_content.stdout

    - name: Apply network configuration
      systemd:
        name: networking
        state: restarted
      async: 60
      poll: 0

    - name: Wait for reconnection with new IP
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 180
        delay: 15
      connection: local
      delegate_to: localhost

    - name: Final verification
      command: hostname -I
      register: final_ips
      changed_when: false

    - name: Display final IP addresses
      debug:
        msg: "Current IP addresses: {{ final_ips.stdout }}"
