---
- name: Direct network configuration change as root
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Get current IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: current_ip
      changed_when: false

    - name: Display current IP
      debug:
        msg: "Current IP: {{ current_ip.stdout }}"

    - name: Create backup of current interfaces
      shell: cp /etc/network/interfaces /etc/network/interfaces.backup.direct.{{ ansible_date_time.epoch }}

    - name: Apply new network configuration using direct shell commands
      shell: |
        # Create new interfaces file
        cat > /etc/network/interfaces << 'EOF'
        # Ansible managed - Direct configuration
        auto lo
        iface lo inet loopback

        auto {{ target_interface }}
        iface {{ target_interface }} inet static
          address {{ new_ip_address }}/{{ subnet_prefix }}
          gateway {{ gateway }}
          dns-nameservers {{ dns_servers }}
          dns-search {{ dns_domain }}
        EOF

    - name: Display the new configuration
      shell: cat /etc/network/interfaces
      register: new_config
      changed_when: false

    - name: Show applied configuration
      debug:
        var: new_config.stdout

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      async: 30
      poll: 0

    - name: Wait for connection recovery
      wait_for_connection:
        timeout: 60
        delay: 10
        sleep: 5

    - name: Verify new IP address
      shell: ip -4 addr show {{ target_interface }} | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1
      register: new_ip
      changed_when: false

    - name: Display final result
      debug:
        msg: |
          NETWORK CONFIGURATION COMPLETED!
          ===============================
          Old IP: {{ current_ip.stdout }}
          New IP: {{ new_ip.stdout }}
          Configuration: {{ "SUCCESS" if new_ip_address == new_ip.stdout else "FAILED - Manual intervention required" }}
          
