---
- name: Change network configuration using netplan
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    target_interface: "{{ target_interface }}"
    new_ip_address: "{{ new_ip_address }}"
    gateway: "{{ gateway }}"
    subnet_prefix: "{{ subnet_prefix }}"
    dns_servers: "{{ dns_servers }}"
    dns_domain: "{{ dns_domain }}"

  tasks:
    - name: Check if netplan is available
      stat:
        path: /etc/netplan
      register: netplan_dir

    - name: Backup existing netplan configs to /tmp
      command: cp -r /etc/netplan /tmp/netplan.backup
      when: netplan_dir.stat.exists
      args:
        creates: /tmp/netplan.backup

    - name: Create new netplan configuration
      copy:
        content: |
          network:
            version: 2
            ethernets:
              {{ target_interface }}:
                dhcp4: no
                addresses:
                  - {{ new_ip_address }}/{{ subnet_prefix }}
                routes:
                  - to: default
                    via: {{ gateway }}
                nameservers:
                  addresses: [{{ dns_servers }}]
                  search: [{{ dns_domain }}]
        dest: /tmp/01-netcfg.yaml
        mode: '0644'

    - name: Apply netplan configuration
      copy:
        src: /tmp/01-netcfg.yaml
        dest: /etc/netplan/01-netcfg.yaml
        mode: '0644'
      when: netplan_dir.stat.exists

    - name: Apply netplan
      command: netplan apply
      async: 30
      poll: 0
      when: netplan_dir.stat.exists
      ignore_errors: yes

    - name: Wait for reconnection with new IP
      wait_for_connection:
        host: "{{ new_ip_address }}"
        port: 22
        timeout: 90
        delay: 10
      connection: local
      delegate_to: localhost
      ignore_errors: yes

    - name: Verify new configuration
      command: ip addr show {{ target_interface }}
      register: ip_info
      when: netplan_dir.stat.exists

    - name: Display new configuration
      debug:
        var: ip_info.stdout
      when: netplan_dir.stat.exists
